[package]
name = "fcp"
version = "0.1.0"
authors = ["David ‘Bombe’ Roden <bombe@pterodactylus.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
config = "0.10.1"
